### ISSUE TITLE
TM Bundle - does not work with Marked 2

### ISSUE THREAD

**Issue by edrozenberg** [kotfu/marked-bonus-pack#3]
Hello,

I just tried the TM Bundle, it doesn't work with Marked 2 until I made the necessary changes to the
tmcommands.

Regards,
--Ed

**Comment by kotfu** [comment]
I'd love some more detail about this problem. When I look at the source of the bundle [in github](https://github.com/kotfu/marked-bonus-pack/blob/master/TextMate/Marked%202.tmbundle/Commands/Open%20in%20Marked%202.tmCommand), it appears to me that it should be opening Marked 2. Did you download from from the releases page (at https://github.com/kotfu/marked-bonus-pack/releases)? Or did you use git to clone the repository?

**Comment by edrozenberg** [comment]
I used the github release, I think that's my problem:
Source code (tar.gz) https://github.com/kotfu/marked-bonus-pack/archive/v1.5.tar.gz

I'll use the github snapshot instead.

Regards,
--Ed

**Comment by kotfu** [comment]
To reduce confusion in the future, I have created a new release called [Marked Bonus Pack 2.0](https://github.com/kotfu/marked-bonus-pack/releases/tag/v2.0). I hope the bonus pack is working well for you now.

**Comment by edrozenberg** [comment]
It's working fine now thanks!
