### ISSUE TITLE
Alternate for Vim command

### ISSUE THREAD

**Issue by dixius99** [kotfu/marked-bonus-pack#6]
For whatever reason, I'd rather type a :command vs. using the leader key to launch Marked. To do that, you'd add the following to your .vimrc instead of the command already in readme.md:

     command Marked :silent !open -a Marked\ 2.app '%:p'

The word right after "command" is what triggers the action. It can be anything the user wants, but has to start with a capital letter.

Not sure if you wanted to add this to the readme or not, as an alternative to what is already there.

**Comment by kotfu** [comment]
Thanks for the tip! Added to README in the vim section.
